# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(300, 150))
        MainWindow.setMaximumSize(QtCore.QSize(300, 150))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_1 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_1.setGeometry(QtCore.QRect(0, 0, 300, 150))
        self.frame_1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_1.setObjectName("frame_1")
        self.button_add = QtWidgets.QPushButton(parent=self.frame_1)
        self.button_add.setGeometry(QtCore.QRect(60, 40, 80, 25))
        self.button_add.setObjectName("button_add")
        self.button_multiply = QtWidgets.QPushButton(parent=self.frame_1)
        self.button_multiply.setGeometry(QtCore.QRect(60, 80, 80, 25))
        self.button_multiply.setObjectName("button_multiply")
        self.button_divide = QtWidgets.QPushButton(parent=self.frame_1)
        self.button_divide.setGeometry(QtCore.QRect(160, 80, 80, 25))
        self.button_divide.setObjectName("button_divide")
        self.button_subtract = QtWidgets.QPushButton(parent=self.frame_1)
        self.button_subtract.setGeometry(QtCore.QRect(160, 40, 80, 25))
        self.button_subtract.setObjectName("button_subtract")
        self.label_mode = QtWidgets.QLabel(parent=self.frame_1)
        self.label_mode.setGeometry(QtCore.QRect(115, 10, 70, 25))
        self.label_mode.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_mode.setObjectName("label_mode")
        self.button_subtract.raise_()
        self.button_divide.raise_()
        self.button_add.raise_()
        self.label_mode.raise_()
        self.button_multiply.raise_()
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 300, 150))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_equation = QtWidgets.QLabel(parent=self.frame_2)
        self.label_equation.setGeometry(QtCore.QRect(40, 60, 76, 13))
        self.label_equation.setObjectName("label_equation")
        self.input_answer = QtWidgets.QLineEdit(parent=self.frame_2)
        self.input_answer.setGeometry(QtCore.QRect(130, 60, 113, 20))
        self.input_answer.setObjectName("input_answer")
        self.button_submit = QtWidgets.QPushButton(parent=self.frame_2)
        self.button_submit.setGeometry(QtCore.QRect(50, 100, 75, 23))
        self.button_submit.setObjectName("button_submit")
        self.button_return = QtWidgets.QPushButton(parent=self.frame_2)
        self.button_return.setGeometry(QtCore.QRect(150, 100, 75, 23))
        self.button_return.setObjectName("button_return")
        self.label_correct = QtWidgets.QLabel(parent=self.frame_2)
        self.label_correct.setGeometry(QtCore.QRect(0, 10, 300, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_correct.setFont(font)
        self.label_correct.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_correct.setObjectName("label_correct")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Project 2"))
        self.button_add.setText(_translate("MainWindow", "Addition"))
        self.button_multiply.setText(_translate("MainWindow", "Multiplication"))
        self.button_divide.setText(_translate("MainWindow", "Division"))
        self.button_subtract.setText(_translate("MainWindow", "Subtraction"))
        self.label_mode.setText(_translate("MainWindow", "Select Mode:"))
        self.label_equation.setText(_translate("MainWindow", "Math Problem ="))
        self.button_submit.setText(_translate("MainWindow", "Submit"))
        self.button_return.setText(_translate("MainWindow", "Exit"))
        self.label_correct.setText(_translate("MainWindow", "0 out of 0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
